// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Thor.DataLayer.Data;

#nullable disable

namespace Thor.DataLayer.Migrations.Master
{
    [DbContext(typeof(MasterDbContext))]
    [Migration("20260805095313_InitialMasterCreate")]
    partial class InitialMasterCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("master")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Thor.DataLayer.Models.AuthenticationField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("authentication_fields", "master");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.AuthenticationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connector_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("authentication_types", "master");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.ConnectorConfigField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connector_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("input_type");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("connector_config_fields", "master");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<short>("IsolationTypeId")
                        .HasColumnType("smallint")
                        .HasColumnName("isolation_type_id");

                    b.Property<short>("StatusId")
                        .HasColumnType("smallint")
                        .HasColumnName("status_id");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subdomain");

                    b.Property<short>("TierId")
                        .HasColumnType("smallint")
                        .HasColumnName("tier_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TenantId");

                    b.ToTable("tenant", "auth");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.TenantRouting", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("AppClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_client_Id");

                    b.Property<string>("ClusterEndpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cluster_endpoint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("database_name");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("SecretArn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_arn");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserPoolId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_pool_id");

                    b.HasKey("TenantId");

                    b.ToTable("tenant_routing", "auth");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.AuthenticationField", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.AuthenticationType", "AuthenticationType")
                        .WithMany("AuthenticationFields")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthenticationType");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.TenantRouting", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenant", "Tenant")
                        .WithOne("Routing")
                        .HasForeignKey("Thor.DataLayer.Models.TenantRouting", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.AuthenticationType", b =>
                {
                    b.Navigation("AuthenticationFields");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenant", b =>
                {
                    b.Navigation("Routing");
                });
#pragma warning restore 612, 618
        }
    }
}
