// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Thor.DataLayer.Data;

#nullable disable

namespace Thor.DataLayer.Migrations.Tenant
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260805095331_InitialTenantCreate")]
    partial class InitialTenantCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenant")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.AuthenticationMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("authentication_methods", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.AuthenticationValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("method_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.ToTable("authentication_values", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnalysisCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analysis_completed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CompletedTasks")
                        .HasColumnType("integer")
                        .HasColumnName("completed_tasks");

                    b.Property<DateTimeOffset?>("IngestionCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingestion_completed_at");

                    b.Property<Guid>("ScanConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_config_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("TotalTasks")
                        .HasColumnType("integer")
                        .HasColumnName("total_tasks");

                    b.HasKey("Id");

                    b.HasIndex("ScanConfigId");

                    b.ToTable("scan", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthMethodId")
                        .HasColumnType("uuid")
                        .HasColumnName("auth_method");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("AuthMethodId");

                    b.ToTable("scan_config", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanConnectorConfigValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("config_id");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connector_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ScanConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_config_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ScanConfigId");

                    b.ToTable("scan_connector_config_values", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanSourceMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ScanConfigId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_config_id");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("Id");

                    b.HasIndex("ScanConfigId");

                    b.HasIndex("SourceId");

                    b.ToTable("scan_source_mapping", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("SourceId");

                    b.ToTable("scan_task", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .HasColumnType("text")
                        .HasColumnName("config");

                    b.Property<string>("ConnectorType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("connector_type");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("source", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.WorkflowEntity", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_id");

                    b.Property<string>("ScheduledBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scheduled_by");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("TimeoutAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timeout_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workflow_type");

                    b.HasKey("WorkflowId");

                    b.HasIndex("ScanId");

                    b.ToTable("workflow", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.WorkflowGraph", b =>
                {
                    b.Property<Guid>("ParentWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_workflow_id");

                    b.Property<Guid>("ChildWorkflowId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_workflow_id");

                    b.HasKey("ParentWorkflowId", "ChildWorkflowId");

                    b.HasIndex("ChildWorkflowId");

                    b.ToTable("workflow_graph", "tenant");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.AuthenticationValue", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.AuthenticationMethod", "AuthenticationMethod")
                        .WithMany("AuthenticationValues")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthenticationMethod");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.Scan", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.ScanConfig", "ScanConfig")
                        .WithMany("Scans")
                        .HasForeignKey("ScanConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanConfig");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanConfig", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.AuthenticationMethod", "AuthenticationMethod")
                        .WithMany("ScanConfigs")
                        .HasForeignKey("AuthMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthenticationMethod");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanConnectorConfigValue", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.ScanConfig", "ScanConfig")
                        .WithMany("ConnectorConfigValues")
                        .HasForeignKey("ScanConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanConfig");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanSourceMapping", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.ScanConfig", "ScanConfig")
                        .WithMany("SourceMappings")
                        .HasForeignKey("ScanConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thor.DataLayer.Models.Tenants.Source", "Source")
                        .WithMany("ScanSourceMappings")
                        .HasForeignKey("SourceId");

                    b.Navigation("ScanConfig");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanTask", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.Scan", "Scan")
                        .WithMany("Tasks")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thor.DataLayer.Models.Tenants.Source", "Source")
                        .WithMany("Tasks")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.WorkflowEntity", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.Scan", "Scan")
                        .WithMany("Workflows")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.WorkflowGraph", b =>
                {
                    b.HasOne("Thor.DataLayer.Models.Tenants.WorkflowEntity", "ChildWorkflow")
                        .WithMany()
                        .HasForeignKey("ChildWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thor.DataLayer.Models.Tenants.WorkflowEntity", "ParentWorkflow")
                        .WithMany()
                        .HasForeignKey("ParentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildWorkflow");

                    b.Navigation("ParentWorkflow");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.AuthenticationMethod", b =>
                {
                    b.Navigation("AuthenticationValues");

                    b.Navigation("ScanConfigs");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.Scan", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.ScanConfig", b =>
                {
                    b.Navigation("ConnectorConfigValues");

                    b.Navigation("Scans");

                    b.Navigation("SourceMappings");
                });

            modelBuilder.Entity("Thor.DataLayer.Models.Tenants.Source", b =>
                {
                    b.Navigation("ScanSourceMappings");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
