<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Thor.TaskApi</RootNamespace>
    <AssemblyName>Thor.TaskApi</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\Thor.DataLayer\Thor.DataLayer.csproj" />
    <ProjectReference Include="..\..\shared\Thor.DataConnectionManager\Thor.DataConnectionManager.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="4.0.5" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
  </ItemGroup>

</Project>
